modLoader="javafml"

loaderVersion="[35,)"

license="GNU Lesser General Public License"
[[mods]]
modId="silicon"
version="${file.jarVersion}"
displayName="Silicon: Gempire Add-on"
logoFile="icon.png"
credits="All Original Character credits go to lillemby. Steven Universe and it's ips belong to Cartoon Network and Rebecca Sugar."
authors="lillemby, Eirnin (For help with coding and making the main mod)"
description='''
A Gempire add-on that includes my gem ocs, homeworld building items, and other things you'll find while exploring the world.
'''

[[dependencies.silicon]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silicon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silicon]]
    modId="gempire"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
